```{r setup}

#install packages
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("googlesheets4")) install.packages("googlesheets4")
if (!require("janitor")) install.packages("janitor")
if (!require("lubridate")) install.packages("lubridate")
if (!require("readxl")) install.packages("readxl")
if (!require("MuMIn")) install.packages("MuMIn")
if (!require("MASS")) install.packages("MASS")
if (!require("pscl")) install.packages("pscl")
if (!require("ggokabeito")) install.packages("ggokabeito")
if (!require("remotes")) install.packages("remotes")
#remotes::install_github("trobinj/trtools")

#set working directory to present directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#load libraries
library(tidyverse)
library(googlesheets4)
library(janitor)
library(lubridate)
library(readxl)
library(MuMIn)
library(MASS)
library(pscl)
library(ggokabeito)
library(scales)
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import}
#import tickbot data from Google

data_tb <- read_sheet("https://docs.google.com/spreadsheets/d/1DC0JCGUZPPxh2Eqrvm6OvN99y90eVjn5YXXOFl1Cl4w/edit?usp=sharing", col_types = "Dtcccccnc")
data_tb <- as_tibble(data_tb)

```

```{r data wrangling}
data_tb_tidy <- data_tb %>% 
  clean_names() %>%
  fill(c(date:transect), .direction = "down")

data_tb_tidy <- within(data_tb_tidy,{
  time_tb <- as.POSIXlt(time,format="%Y/%m/%d %H:%M")
  time <- format(time_tb, "%H:%M")
})




```